### ISSUE TITLE
TypeError: page.html.matchAll is not a function 

### ISSUE THREAD

**Issue by steffendolan** [d1urno/nuxt-image-extractor#7]
I'm getting this error during generation:

page.html.matchAll is not a function                                                                                                                                             10:04:41

  at process (node_modules/nuxt-image-extractor/lib/module.js:35:31)
  at Extract.nuxt.hook (node_modules/nuxt-image-extractor/lib/module.js:23:18)
  at o (node_modules/hable/dist/hable.js:1:1052)
  at o.then.o (node_modules/hable/dist/hable.js:1:270)

**Comment by d1urno** [comment]
Duplicate of #3
